export interface MedProfile {
  name: string;
  genericName?: string;
  brandNames: string[];
  drugClass: string;
  type: "rescue" | "preventive" | "supplement" | "other";
  mechanism: string;
  migraineUse: string;
  dosing: string;
  onset: string;
  sideEffects: string[];
  warnings: string[];
  contraindications: string[];
  interactsWith: string[];
  pregnancy: string;
  migraineRating: "first-line" | "second-line" | "adjunct" | "not-recommended";
}

export const MED_DB: Record<string, MedProfile> = {
  sumatriptan: {
    name: "Sumatriptan",
    brandNames: ["Imitrex", "Tosymra"],
    drugClass: "Triptan (5-HT₁B/₁D agonist)",
    type: "rescue",
    mechanism: "Selectively activates serotonin 5-HT₁B/₁D receptors, causing vasoconstriction of dilated intracranial vessels and inhibiting nociceptive neurotransmission.",
    migraineUse: "Acute treatment of migraine with or without aura. Most effective when taken early in attack.",
    dosing: "50–100mg oral; 6mg subcutaneous; 5–20mg nasal spray. Max 200mg/day.",
    onset: "30–60 min oral; ~15 min subcutaneous",
    sideEffects: ["Chest tightness/pressure", "Tingling/flushing", "Dizziness", "Fatigue", "Nausea", "Injection site reactions (SC)"],
    warnings: ["Cardiovascular risk — avoid with CAD, uncontrolled hypertension", "Medication overuse headache (>10 days/month)", "Serotonin syndrome risk with SSRIs/SNRIs"],
    contraindications: ["Hemiplegic/basilar migraine", "Ischemic heart disease", "Uncontrolled HTN", "Within 24h of another triptan or ergot"],
    interactsWith: ["MAOIs", "SSRIs/SNRIs (serotonin syndrome)", "Ergotamines", "Other triptans"],
    pregnancy: "Pregnancy Category C — limited data; use only if clearly needed.",
    migraineRating: "first-line",
  },
  rizatriptan: {
    name: "Rizatriptan",
    brandNames: ["Maxalt", "Maxalt-MLT"],
    drugClass: "Triptan (5-HT₁B/₁D agonist)",
    type: "rescue",
    mechanism: "Same mechanism as sumatriptan; higher oral bioavailability (~45%) and faster CNS penetration.",
    migraineUse: "Acute migraine treatment. Faster onset than oral sumatriptan, useful for rapid relief.",
    dosing: "5–10mg oral or ODT. Max 30mg/day. Reduce to 5mg if on propranolol.",
    onset: "~30 min (faster than sumatriptan oral)",
    sideEffects: ["Somnolence", "Dizziness", "Nausea", "Chest/throat tightness", "Dry mouth"],
    warnings: ["Same cardiovascular precautions as sumatriptan", "Dose reduction needed with propranolol (CYP interaction)", "Medication overuse headache"],
    contraindications: ["Same as sumatriptan", "Within 24h of another triptan"],
    interactsWith: ["Propranolol (increases rizatriptan exposure ~70%)", "MAOIs", "SSRIs/SNRIs", "Ergotamines"],
    pregnancy: "Pregnancy Category C.",
    migraineRating: "first-line",
  },
  ubrogepant: {
    name: "Ubrogepant",
    brandNames: ["Ubrelvy"],
    drugClass: "CGRP receptor antagonist (gepant)",
    type: "rescue",
    mechanism: "Blocks the calcitonin gene-related peptide (CGRP) receptor, interrupting the pain-signaling cascade in migraine without vasoconstriction.",
    migraineUse: "Acute migraine. Safe in patients with cardiovascular contraindications to triptans. Can be used same day as preventive CGRP inhibitors.",
    dosing: "50–100mg oral. Second dose (50–100mg) after ≥2h if needed. Max 200mg/24h.",
    onset: "~60 min",
    sideEffects: ["Nausea", "Somnolence", "Dry mouth"],
    warnings: ["CYP3A4 interactions — avoid strong CYP3A4 inducers/inhibitors", "Hepatic impairment may require dose adjustment"],
    contraindications: ["Strong CYP3A4 inhibitors (e.g., clarithromycin, ketoconazole)"],
    interactsWith: ["CYP3A4 inhibitors (increase exposure)", "CYP3A4 inducers (reduce efficacy)", "Lecanemab"],
    pregnancy: "No adequate human data; animal studies show embryotoxicity at high doses.",
    migraineRating: "second-line",
  },
  rimegepant: {
    name: "Rimegepant",
    brandNames: ["Nurtec ODT"],
    drugClass: "CGRP receptor antagonist (gepant)",
    type: "rescue",
    mechanism: "CGRP receptor blockade. Unique among gepants — approved for BOTH acute and preventive migraine use (every-other-day dosing for prevention).",
    migraineUse: "Acute migraine AND preventive therapy (75mg every other day). Only drug FDA-approved for both indications.",
    dosing: "75mg ODT. For acute: single dose. For prevention: 75mg every other day.",
    onset: "~60 min",
    sideEffects: ["Nausea", "Abdominal pain (rare)", "Hypersensitivity reactions"],
    warnings: ["CYP3A4/P-gp substrate — multiple drug interactions", "Hepatic impairment: avoid in severe cases"],
    contraindications: ["Strong CYP3A4 inhibitors", "Severe hepatic impairment"],
    interactsWith: ["CYP3A4 inhibitors/inducers", "P-glycoprotein inhibitors"],
    pregnancy: "No adequate human data.",
    migraineRating: "second-line",
  },
  topiramate: {
    name: "Topiramate",
    brandNames: ["Topamax", "Trokendi XR", "Qudexy XR"],
    drugClass: "Antiepileptic (sulfamate-substituted monosaccharide)",
    type: "preventive",
    mechanism: "Multiple mechanisms: Na⁺/Ca²⁺ channel blockade, GABA-A potentiation, AMPA/kainate antagonism, carbonic anhydrase inhibition.",
    migraineUse: "First-line preventive therapy. Reduces migraine frequency by ~50% in responders. Takes 2–3 months for full effect.",
    dosing: "25mg nightly, titrate slowly to 50–100mg/day in divided doses. Slow titration reduces side effects.",
    onset: "Preventive effect: 6–12 weeks",
    sideEffects: ["Cognitive slowing/word-finding difficulty ('Dopamax')", "Paresthesias (toes/fingers)", "Weight loss", "Kidney stones", "Fatigue", "Nausea", "Mood changes"],
    warnings: ["Teratogenic — avoid in pregnancy (neural tube defects)", "Metabolic acidosis", "Acute myopia/glaucoma (rare but serious)", "Cognitive impairment"],
    contraindications: ["Pregnancy (Category D)", "Recent metabolic acidosis"],
    interactsWith: ["Oral contraceptives (reduces efficacy)", "Lithium", "Carbonic anhydrase inhibitors (kidney stone risk)", "Valproate (encephalopathy risk)"],
    pregnancy: "Category D — significant teratogen; strongly avoid.",
    migraineRating: "first-line",
  },
  propranolol: {
    name: "Propranolol",
    brandNames: ["Inderal", "Inderal LA", "InnoPran XL"],
    drugClass: "Non-selective beta-blocker",
    type: "preventive",
    mechanism: "Non-selective β₁/β₂ blockade reduces sympathetic tone; may stabilize cortical spreading depression and reduce vasoreactivity.",
    migraineUse: "First-line preventive therapy. Also treats comorbid hypertension, angina, anxiety, and essential tremor.",
    dosing: "40–240mg/day (IR in 2–3 divided doses; LA once daily). Start 40mg BID, titrate monthly.",
    onset: "Preventive effect: 4–8 weeks",
    sideEffects: ["Fatigue/lethargy", "Cold extremities", "Bradycardia", "Depression/mood changes", "Vivid dreams", "Exercise intolerance", "Weight gain"],
    warnings: ["Abrupt discontinuation → rebound angina/hypertension", "Masks hypoglycemia symptoms in diabetics", "Bronchospasm in asthma/COPD"],
    contraindications: ["Asthma/reactive airway disease", "Heart block > 1st degree", "Severe bradycardia", "Decompensated HF", "Raynaud's syndrome"],
    interactsWith: ["Rizatriptan (increases rizatriptan exposure 70%)", "Calcium channel blockers", "Antidiabetics", "MAOIs", "Digoxin"],
    pregnancy: "Category C — crosses placenta; neonatal bradycardia/hypoglycemia possible.",
    migraineRating: "first-line",
  },
  amitriptyline: {
    name: "Amitriptyline",
    brandNames: ["Elavil"],
    drugClass: "Tricyclic antidepressant (TCA)",
    type: "preventive",
    mechanism: "Inhibits norepinephrine and serotonin reuptake; strong anticholinergic and antihistamine activity. Central pain-modulation via descending pathways.",
    migraineUse: "Preventive migraine therapy (off-label). Particularly useful in patients with comorbid insomnia, depression, or chronic daily headache.",
    dosing: "10–25mg nightly; titrate to 75–150mg/night as tolerated. Low doses effective for migraine.",
    onset: "4–8 weeks for preventive effect",
    sideEffects: ["Sedation/morning grogginess", "Dry mouth", "Constipation", "Weight gain", "Urinary retention", "Blurred vision", "Orthostatic hypotension", "Cardiac arrhythmias (at high doses)"],
    warnings: ["QTc prolongation at high doses — ECG monitoring advised", "Anticholinergic toxicity in elderly", "Serotonin syndrome risk"],
    contraindications: ["Recent MI", "Heart block", "Narrow-angle glaucoma", "Within 14 days of MAOIs"],
    interactsWith: ["MAOIs (serotonin syndrome/hypertensive crisis)", "SSRIs/SNRIs", "Anticholinergics", "CNS depressants", "QT-prolonging drugs"],
    pregnancy: "Category C — neonatal withdrawal reported.",
    migraineRating: "second-line",
  },
  erenumab: {
    name: "Erenumab",
    brandNames: ["Aimovig"],
    drugClass: "Anti-CGRP receptor monoclonal antibody",
    type: "preventive",
    mechanism: "Humanized IgG2 monoclonal antibody that blocks the CGRP receptor. Monthly subcutaneous injection. Highly specific with minimal systemic drug interactions.",
    migraineUse: "Preventive therapy for episodic and chronic migraine. First FDA-approved CGRP antibody. Reduces migraine days/month.",
    dosing: "70mg SC monthly (may increase to 140mg monthly if inadequate response).",
    onset: "Response often seen within 1 month; full assessment at 3–6 months",
    sideEffects: ["Injection site reactions", "Constipation (dose-dependent, can be severe)", "Hypertension (rare)", "Muscle spasm"],
    warnings: ["Serious constipation — may require treatment", "Limited long-term safety data in cardiovascular disease"],
    contraindications: ["Known hypersensitivity to erenumab"],
    interactsWith: ["Minimal — biological with few cytochrome interactions"],
    pregnancy: "No adequate data — IgG antibodies cross placenta in 2nd/3rd trimester; generally avoided.",
    migraineRating: "second-line",
  },
  ibuprofen: {
    name: "Ibuprofen",
    brandNames: ["Advil", "Motrin"],
    drugClass: "NSAID (non-selective COX inhibitor)",
    type: "rescue",
    mechanism: "Non-selective inhibition of COX-1 and COX-2 reduces prostaglandin synthesis, decreasing neuroinflammation and sensitization.",
    migraineUse: "Effective for mild-to-moderate migraine. Often first-line in patients with infrequent attacks. Lower risk of MOH vs. triptans.",
    dosing: "400–800mg at onset. Repeat 400mg after 6h if needed. Max 1200mg/day for OTC use.",
    onset: "~30–60 min",
    sideEffects: ["GI irritation/ulcers", "Renal impairment", "Fluid retention", "Hypertension", "Cardiovascular risk with chronic use", "Headache rebound with overuse"],
    warnings: ["GI bleeding risk — take with food", "Avoid in renal impairment", "Increased CV risk with chronic use", "Medication overuse headache >15 days/month"],
    contraindications: ["Active GI bleeding/ulcer", "Severe renal/hepatic impairment", "Late pregnancy (Category D after 30 weeks)"],
    interactsWith: ["Anticoagulants (bleeding risk)", "Lithium (increases levels)", "ACE inhibitors", "Corticosteroids", "Other NSAIDs"],
    pregnancy: "Category C (Category D after 30 weeks) — avoid in 3rd trimester.",
    migraineRating: "first-line",
  },
  naproxen: {
    name: "Naproxen",
    brandNames: ["Aleve", "Naprosyn", "Anaprox"],
    drugClass: "NSAID (non-selective COX inhibitor)",
    type: "rescue",
    mechanism: "COX-1/COX-2 inhibition; longer half-life (~12–17h) than ibuprofen allows twice-daily dosing.",
    migraineUse: "Acute migraine; also used preventively (naproxen sodium 550mg BID for menstrual migraine prevention).",
    dosing: "500–550mg at onset; may repeat 500mg after 1h. Max 1000mg/day acute use.",
    onset: "~1–2h (slower than ibuprofen but longer duration)",
    sideEffects: ["GI effects (similar to ibuprofen)", "Headache rebound", "Fluid retention", "Dizziness"],
    warnings: ["Same GI/CV/renal precautions as ibuprofen", "Longer half-life increases accumulation risk"],
    contraindications: ["Same as ibuprofen"],
    interactsWith: ["Same as ibuprofen"],
    pregnancy: "Category C/D (3rd trimester).",
    migraineRating: "first-line",
  },
};
