/**
 * Shared sample migraine data used by both the Calendar and History pages.
 * UserEntry-compatible shape so both pages use the same source of truth.
 */

export type SampleEntry = {
  id: number;
  date: string;           // "MMM d" format e.g. "Feb 1"
  isoDate: string;        // "yyyy-MM-dd" for calendar matching
  severity: number;
  durationMin: number;
  area: string;
  symptoms: string[];
  triggers: string[];
  meds: string[];
  weather: string;
  sleep: number;
  caffeine: number;
  water: number;          // glasses
  stress: string;
  skippedMeal: boolean;
  notes: string;
  hormonalStatus?: string[];
};

export const SAMPLE_MIGRAINE_DATA: SampleEntry[] = [
  { id: 101, isoDate: "2026-02-01", date: "Feb 1",  severity: 7,  durationMin: 165, area: "Right Temporal",     symptoms: ["Throbbing Pain", "Light Sensitivity"], triggers: ["Poor Sleep", "Caffeine", "Stress"],             meds: ["Sumatriptan"],  weather: "Cloudy",         sleep: 6.0, caffeine: 120, water: 6, stress: "High",      skippedMeal: false, notes: "Woke up tired; late coffee" },
  { id: 102, isoDate: "2026-02-02", date: "Feb 2",  severity: 9,  durationMin: 135, area: "Left Orbital",       symptoms: ["Severe Head Pain", "Nausea", "Aura"],   triggers: ["Skipped Meal", "Dehydration", "Poor Sleep", "Screen Time", "Rain/Pressure"], meds: ["Ibuprofen"],    weather: "Rain",           sleep: 4.5, caffeine: 0,   water: 4, stress: "Very High", skippedMeal: true,  notes: "Skipped breakfast; long screen time" },
  { id: 103, isoDate: "2026-02-04", date: "Feb 4",  severity: 5,  durationMin: 165, area: "Bifrontal",          symptoms: ["Dull Ache", "Fatigue"],                 triggers: ["Poor Sleep", "Stress"],                        meds: [],               weather: "Overcast",       sleep: 5.0, caffeine: 80,  water: 5, stress: "Moderate",  skippedMeal: false, notes: "Woke early for work; mild stress" },
  { id: 104, isoDate: "2026-02-05", date: "Feb 5",  severity: 8,  durationMin: 165, area: "Occipital",          symptoms: ["Severe Head Pain", "Nausea", "Sound Sensitivity"], triggers: ["Weather/Storm", "Skipped Meal", "Noise", "Caffeine"], meds: ["Sumatriptan"],  weather: "Storm",          sleep: 5.5, caffeine: 150, water: 5, stress: "High",      skippedMeal: true,  notes: "Loud office; storm outside" },
  { id: 105, isoDate: "2026-02-07", date: "Feb 7",  severity: 6,  durationMin: 100, area: "Fronto-Temporal",    symptoms: ["Throbbing Pain", "Screen Fatigue"],     triggers: ["Screen Time", "Stress"],                       meds: ["Acetaminophen"],weather: "Cloudy",         sleep: 6.5, caffeine: 90,  water: 5, stress: "Moderate",  skippedMeal: false, notes: "Headache after late night coding" },
  { id: 106, isoDate: "2026-02-09", date: "Feb 9",  severity: 4,  durationMin: 90,  area: "Vertex",             symptoms: ["Dull Ache", "Nausea"],                  triggers: ["Stress", "Rain/Pressure", "Poor Sleep"],       meds: [],               weather: "Rain",           sleep: 5.0, caffeine: 50,  water: 6, stress: "High",      skippedMeal: false, notes: "Work deadline; light nausea" },
  { id: 107, isoDate: "2026-02-10", date: "Feb 10", severity: 8,  durationMin: 90,  area: "Right Occipital",    symptoms: ["Severe Head Pain", "Vomiting", "Noise Sensitivity"], triggers: ["Stress", "Weather/Storm", "Skipped Meal", "Caffeine", "Poor Sleep", "Noise"], meds: ["Sumatriptan"],  weather: "Storm",          sleep: 4.0, caffeine: 200, water: 5, stress: "Very High", skippedMeal: true,  notes: "Major stress at work; loud environment" },
  { id: 108, isoDate: "2026-02-12", date: "Feb 12", severity: 5,  durationMin: 140, area: "Bifrontal",          symptoms: ["Dull Ache", "Fatigue", "Brain Fog"],    triggers: ["Poor Sleep", "Hormonal/Menstrual"],            meds: ["Ibuprofen"],    weather: "Overcast",       sleep: 5.5, caffeine: 80,  water: 5, stress: "Moderate",  skippedMeal: false, notes: "Early meeting; mild cramps", hormonalStatus: ["Menstruating"] },
  { id: 109, isoDate: "2026-02-13", date: "Feb 13", severity: 7,  durationMin: 155, area: "Left Temporal",      symptoms: ["Throbbing Pain", "Light Sensitivity", "Nausea"], triggers: ["Skipped Meal", "Rain/Pressure", "Screen Time", "Caffeine", "Hormonal/Menstrual"], meds: ["Sumatriptan"],  weather: "Rain",           sleep: 5.0, caffeine: 160, water: 4, stress: "High",      skippedMeal: true,  notes: "Skipped lunch; high screen time", hormonalStatus: ["Menstruating"] },
  { id: 110, isoDate: "2026-02-15", date: "Feb 15", severity: 6,  durationMin: 140, area: "Frontal",            symptoms: ["Dull Ache", "Fatigue"],                 triggers: ["Stress", "Screen Time"],                       meds: [],               weather: "Cloudy",         sleep: 6.0, caffeine: 110, water: 6, stress: "Moderate",  skippedMeal: false, notes: "Headache after long meeting" },
  { id: 111, isoDate: "2026-02-16", date: "Feb 16", severity: 5,  durationMin: 90,  area: "Temporal Band",      symptoms: ["Throbbing Pain", "Light Sensitivity"],  triggers: ["Screen Time", "Bright Light", "Caffeine"],     meds: ["Acetaminophen"],weather: "Clear",          sleep: 6.5, caffeine: 180, water: 5, stress: "Moderate",  skippedMeal: false, notes: "Evening screen time; bright room" },
  { id: 112, isoDate: "2026-02-18", date: "Feb 18", severity: 8,  durationMin: 150, area: "Right Periorbital",  symptoms: ["Severe Head Pain", "Nausea", "Aura"],   triggers: ["Stress", "Skipped Meal", "Rain/Pressure", "Poor Sleep", "Hormonal/Menstrual"], meds: ["Sumatriptan"],  weather: "Rain",           sleep: 4.5, caffeine: 70,  water: 5, stress: "Very High", skippedMeal: true,  notes: "Severe stress; skipped breakfast", hormonalStatus: ["Menstruating", "Luteal"] },
  { id: 113, isoDate: "2026-02-19", date: "Feb 19", severity: 3,  durationMin: 90,  area: "Bifrontal",          symptoms: ["Dull Ache"],                            triggers: ["Hormonal/Menstrual"],                          meds: [],               weather: "Overcast",       sleep: 7.0, caffeine: 90,  water: 6, stress: "Mild",      skippedMeal: false, notes: "Mild headache; resolved with rest", hormonalStatus: ["Menstruating"] },
  { id: 114, isoDate: "2026-03-02", date: "Mar 2",  severity: 6,  durationMin: 51,  area: "Periorbital",        symptoms: ["Throbbing Pain", "Fatigue"],            triggers: ["Hormonal/Menstrual", "Caffeine"],              meds: ["Frovatriptan"], weather: "Light Rain",     sleep: 8.6, caffeine: 139, water: 7, stress: "Mild",      skippedMeal: false, notes: "Busy day but felt okay", hormonalStatus: ["Menstruating"] },
  { id: 115, isoDate: "2026-03-03", date: "Mar 3",  severity: 4,  durationMin: 193, area: "Left Temporal",      symptoms: ["Dull Ache", "Neck Tension"],            triggers: ["Stress"],                                      meds: ["Topiramate"],   weather: "Overcast",       sleep: 6.5, caffeine: 88,  water: 8, stress: "High",      skippedMeal: false, notes: "Household chores most of day" },
  { id: 116, isoDate: "2026-03-04", date: "Mar 4",  severity: 10, durationMin: 219, area: "Frontal",            symptoms: ["Severe Head Pain", "Nausea", "Vomiting"], triggers: ["Disrupted Sleep", "Dehydration"],           meds: ["Ibuprofen"],    weather: "Cloudy",         sleep: 8.4, caffeine: 6,   water: 5, stress: "Mild",      skippedMeal: false, notes: "Slept late; early alarm disrupted" },
  { id: 117, isoDate: "2026-03-06", date: "Mar 6",  severity: 3,  durationMin: 81,  area: "Bifrontal",          symptoms: ["Dull Ache", "Light Sensitivity"],       triggers: ["Bright Light", "Stress"],                      meds: ["Excedrin"],     weather: "Snow",           sleep: 5.9, caffeine: 116, water: 8, stress: "Moderate",  skippedMeal: false, notes: "Meetings in bright room" },
  { id: 118, isoDate: "2026-03-07", date: "Mar 7",  severity: 7,  durationMin: 135, area: "Right Orbital",      symptoms: ["Eye Pain", "Screen Fatigue", "Neck Tension", "Brain Fog"], triggers: ["Screen Time", "Caffeine", "Poor Sleep"], meds: ["Naproxen"],     weather: "Foggy",          sleep: 4.2, caffeine: 249, water: 8, stress: "Very High", skippedMeal: false, notes: "Long coding session; forgot breaks" },
  { id: 119, isoDate: "2026-03-08", date: "Mar 8",  severity: 9,  durationMin: 51,  area: "Vertex",             symptoms: ["Severe Head Pain", "Nausea", "Dizziness"], triggers: ["Travel", "Caffeine", "Stress", "Weather/Storm"], meds: ["Ibuprofen"],    weather: "Snow",           sleep: 5.9, caffeine: 260, water: 5, stress: "Very High", skippedMeal: false, notes: "Travel day; irregular meals" },
  { id: 120, isoDate: "2026-03-09", date: "Mar 9",  severity: 8,  durationMin: 173, area: "Left Temporal",      symptoms: ["Throbbing Pain", "Neck Tension", "Fatigue"], triggers: ["Barometric Pressure", "Caffeine"],         meds: ["Naproxen"],     weather: "Foggy",          sleep: 6.9, caffeine: 168, water: 9, stress: "Moderate",  skippedMeal: false, notes: "Outdoor walk; low phone use" },
  { id: 121, isoDate: "2026-03-12", date: "Mar 12", severity: 5,  durationMin: 136, area: "Occipital",          symptoms: ["Dull Ache", "Fatigue"],                 triggers: ["Poor Sleep", "Hormonal/Menstrual"],            meds: ["Sumatriptan"],  weather: "Partly Cloudy",  sleep: 5.1, caffeine: 24,  water: 6, stress: "Moderate",  skippedMeal: false, notes: "Gym in morning; hydrated well", hormonalStatus: ["Menstruating"] },
  { id: 122, isoDate: "2026-03-13", date: "Mar 13", severity: 9,  durationMin: 82,  area: "Frontal",            symptoms: ["Severe Head Pain", "Nausea", "Aura", "Brain Fog"], triggers: ["Stress", "Weather/Storm", "Skipped Meal", "Poor Sleep", "Hormonal/Menstrual"], meds: ["Rizatriptan"],  weather: "Thunderstorm",   sleep: 4.4, caffeine: 13,  water: 5, stress: "Very High", skippedMeal: true,  notes: "Argued with colleague; thunderstorm", hormonalStatus: ["Menstruating"] },
  { id: 123, isoDate: "2026-03-15", date: "Mar 15", severity: 3,  durationMin: 61,  area: "Right Parietal",     symptoms: ["Dull Ache", "Fatigue"],                 triggers: ["Travel", "Skipped Meal", "Poor Sleep", "Hormonal/Menstrual"], meds: ["Acetaminophen"], weather: "Light Rain",    sleep: 4.6, caffeine: 177, water: 7, stress: "Moderate",  skippedMeal: true,  notes: "Travel day; irregular meals", hormonalStatus: ["Menstruating"] },
  { id: 124, isoDate: "2026-03-17", date: "Mar 17", severity: 5,  durationMin: 49,  area: "Right Temporal",     symptoms: ["Throbbing Pain"],                       triggers: ["Caffeine", "Rain/Pressure"],                   meds: ["Topiramate"],   weather: "Light Rain",     sleep: 7.3, caffeine: 201, water: 7, stress: "Mild",      skippedMeal: false, notes: "Busy day but felt okay" },
  { id: 125, isoDate: "2026-03-18", date: "Mar 18", severity: 9,  durationMin: 129, area: "Bilateral Temporal", symptoms: ["Severe Head Pain", "Vomiting", "Sound Sensitivity", "Aura"], triggers: ["Weather/Storm", "Travel", "Skipped Meal", "Caffeine", "Stress"], meds: ["Zolmitriptan"],  weather: "Storm",          sleep: 7.6, caffeine: 235, water: 9, stress: "Very High", skippedMeal: true,  notes: "Travel day; irregular meals" },
  { id: 126, isoDate: "2026-03-20", date: "Mar 20", severity: 6,  durationMin: 151, area: "Periorbital",        symptoms: ["Throbbing Pain", "Fatigue"],            triggers: ["Travel", "Skipped Meal", "Caffeine"],          meds: ["Rizatriptan"],  weather: "Snow",           sleep: 8.1, caffeine: 225, water: 8, stress: "Moderate",  skippedMeal: true,  notes: "Travel day; irregular meals" },
  { id: 127, isoDate: "2026-03-21", date: "Mar 21", severity: 7,  durationMin: 149, area: "Right Orbital",      symptoms: ["Eye Pain", "Light Sensitivity", "Throbbing"], triggers: ["Bright Light", "Skipped Meal", "Hormonal/Menstrual"], meds: ["Ibuprofen"],    weather: "Clear",          sleep: 7.3, caffeine: 94,  water: 6, stress: "High",      skippedMeal: true,  notes: "Lots of meetings in bright room", hormonalStatus: ["Menstruating", "Luteal"] },
  { id: 128, isoDate: "2026-03-23", date: "Mar 23", severity: 7,  durationMin: 193, area: "Left Orbital",       symptoms: ["Throbbing Pain", "Screen Fatigue"],     triggers: ["Screen Time", "Caffeine", "Hormonal/Menstrual"], meds: ["Ibuprofen"],    weather: "Cloudy",         sleep: 6.0, caffeine: 160, water: 5, stress: "Moderate",  skippedMeal: false, notes: "Long coding session; forgot breaks", hormonalStatus: ["Menstruating"] },
  { id: 129, isoDate: "2026-03-24", date: "Mar 24", severity: 8,  durationMin: 66,  area: "Occipital",          symptoms: ["Throbbing Pain", "Neck Tension", "Nausea"], triggers: ["Caffeine", "Poor Sleep", "Rain/Pressure"],   meds: ["Rizatriptan"],  weather: "Light Rain",     sleep: 4.4, caffeine: 224, water: 5, stress: "Very High", skippedMeal: false, notes: "Travel day; irregular meals" },
  { id: 130, isoDate: "2026-03-26", date: "Mar 26", severity: 10, durationMin: 213, area: "Periorbital",        symptoms: ["Severe Head Pain", "Nausea", "Light Sensitivity"], triggers: ["Travel", "Stress", "Caffeine"],      meds: ["Eletriptan"],   weather: "Cloudy",         sleep: 6.7, caffeine: 151, water: 8, stress: "Very High", skippedMeal: false, notes: "Travel day; irregular meals", hormonalStatus: ["Menstruating"] },
  { id: 131, isoDate: "2026-03-27", date: "Mar 27", severity: 3,  durationMin: 48,  area: "Left Temporal",      symptoms: ["Dull Ache", "Fatigue"],                 triggers: ["Caffeine", "Skipped Meal", "Poor Sleep", "Screen Time"], meds: ["Naproxen"],     weather: "Light Rain",     sleep: 5.1, caffeine: 243, water: 7, stress: "High",      skippedMeal: true,  notes: "Long coding session; forgot breaks" },
];
